dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate
script:
  - python -m unittest discover #coverage run manage.py test 