version: "3"

services:
  web:
    container_name: ebblify
    command: python /code/manage.py runserver 0.0.0.0:8000
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
  db:
    container_name: postgres
    hostname: db
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
