# Generated by Django 2.1.1 on 2018-09-13 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='authorone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_first_profile', to=settings.AUTH_USER_MODEL, verbose_name='Author One'),
        ),
        migrations.AddField(
            model_name='message',
            name='authortwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_second_profile', to=settings.AUTH_USER_MODEL, verbose_name='Author Two'),
        ),
    ]
